#!/bin/bash
if [[ "$#" -eq "0" ]]; then
  echo "You need to provide the test program name (without extension & situated in the directory test)"
else
  java -cp antlr-3.5.2-complete.jar:src VslComp test/$1 -debug
  ./nachos/asm2bin.sh $1
  cd nachos/
  ./exec.sh $1
fi
